stego:stego.c ../src/epoll.c ../src/socketwrappers.c ../src/stego_utils.cpp  ../src/EasyBMP.cpp ../src/encrypt_utils.cpp
	g++ -g -o stego stego.c ../src/epoll.c ../src/socketwrappers.c ../src/stego_utils.cpp  ../src/EasyBMP.cpp ../src/encrypt_utils.cpp -lcrypto -fpermissive -fno-stack-protector
